// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simply.Sales.DLL.Context;

namespace Simply.Sales.DLL.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20210725204544_UpdateDelivery4")]
    partial class UpdateDelivery4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Simply.Sales.DLL.Models.Clients.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Clients.ClientToDeliveryZone", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discription")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId", "DeliveryZoneId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("ClientsToDeliveryZones");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Delivery.DeliveryCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeliveryCities");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Delivery.DeliveryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinPriceForFreeDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("DeliveryZones");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Orders.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReceiving")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NeedDelivery")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Clients.ClientToDeliveryZone", b =>
                {
                    b.HasOne("Simply.Sales.DLL.Models.Clients.Client", "Client")
                        .WithMany("DeliveryZones")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Simply.Sales.DLL.Models.Delivery.DeliveryZone", "DeliveryZone")
                        .WithMany("Clients")
                        .HasForeignKey("DeliveryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Delivery.DeliveryZone", b =>
                {
                    b.HasOne("Simply.Sales.DLL.Models.Delivery.DeliveryCity", "City")
                        .WithMany("Zones")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Orders.BasketItem", b =>
                {
                    b.HasOne("Simply.Sales.DLL.Models.Orders.Order", "Order")
                        .WithMany("Basket")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Orders.Order", b =>
                {
                    b.HasOne("Simply.Sales.DLL.Models.Clients.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Simply.Sales.DLL.Models.Delivery.DeliveryZone", "DeliveryZone")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryZoneId");

                    b.Navigation("Client");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Clients.Client", b =>
                {
                    b.Navigation("DeliveryZones");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Delivery.DeliveryCity", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Delivery.DeliveryZone", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Simply.Sales.DLL.Models.Orders.Order", b =>
                {
                    b.Navigation("Basket");
                });
#pragma warning restore 612, 618
        }
    }
}
